repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.101.1
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      name: terraform_tflint_root
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      exclude: ^modules/
    - id: terraform_tflint
      name: terraform_tflint_modules
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint-modules.hcl
      files: ^modules/
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
